language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

before_install:
  - npm install

script:
  - npm run build

deploy:
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    local_dir: build
    bucket: myvoteapp
    application: MyVoteApp
    deployment_group: MyVote-Dev
    upload-dir: travis-builds
    on:
      branch: dev
  - provider: codedeploy
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: myvoteapp
    key: travis-builds
    application: MyVoteApp
    deployment_group: MyVote-Dev
    region: us-east-1
    on:
      branch: dev
