language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

before_install:
  - npm i

script:
  - npm run build

deploy:
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    local_dir: build
    skip_cleanup: true
    bucket: myvoteapp
    application: MyVoteApp
    deployment_group: MyVote-Dev
  - provider: codedeploy
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: myvoteapp
    application: MyVoteApp
    deployment_group: MyVote-Dev
    region: us-east-1
