language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

before_install:
  - npm install

before_deploy:
  - npm run build

script:
  - zip -r myvoteapp.zip build
  - mkdir -p myvote_deploy
  - mv myvoteapp.zip myvote_deploy/myvoteapp.zip
# deploy:
#   - provider: s3
#     access_key_id: $AWS_KEY
#     secret_access_key: $AWS_SECRET
#     local_dir: myvote_deploy
#     bucket: myvoteapp
#     application: MyVoteApp
#     deployment_group: MyVote-Dev
#     on:
#       branch: dev
#   - provider: codedeploy
#     access_key_id: $AWS_KEY
#     secret_access_key: $AWS_SECRET
#     bucket: myvoteapp
#     key: myvoteapp.zip
#     application: MyVoteApp
#     deployment_group: MyVote-Dev
#     region: us-east-1
#     on:
#       branch: dev
